version: 0.1
environment_variables:
    plaintext:
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g node-sass
            - npm install -g @angular/cli
            - npm install -g @angular/core
            - npm install --save-dev @angular-devkit/build-angular
            - npm link
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
            - cd dist/Soundmarker-sass && mv *.* .. && cd ..
            - cp -r server/.htaccess dist
            - cp -r .ebextensions dist
            - cp -r server/* dist
    post_build:
         commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: no