// Generated by CoffeeScript 1.7.1
(function() {
  var key, val, _ref;

  _ref = require('../node_modules/av/src/aurora');
  for (key in _ref) {
    val = _ref[key];
    exports[key] = val;
  }

  require('../node_modules/av/src/devices/webaudio');

  require('../node_modules/av/src/devices/mozilla');

}).call(this);
